model:
  version: v3
  sequence_length: 8
  base_channels: 64
  dropout: 0.0

dataset:
  processed_root: dataset/processed/tracknet_dataset_512x288
  sequence_length: 8
  frame_stride: 1
  train_split_file: dataset/processed/tracknet_dataset_512x288/splits/train.txt
  val_split_file: dataset/processed/tracknet_dataset_512x288/splits/val.txt

train:
  experiment_name: tracknet_v3_tracker
  output_root: outputs/train
  epochs: 50
  batch_size: 2
  workers: 8
  persistent_workers: true
  prefetch_factor: 2
  optimizer: Adam
  lr: 0.001
  loss: wbce
  device: auto
  amp: true
  tensorboard: true
  launch_tensorboard: true
  tensorboard_port: 6006
  tensorboard_images: true
  tensorboard_hparams: true
  tensorboard_histograms: false
  tensorboard_profiler: false
  log_every_steps: 20
  tensorboard_flush_secs: 30
  tensorboard_max_queue: 100
  seed: 26
