model:
  version: v1
  sequence_length: 3
  base_channels: 64
  dropout: 0.0

dataset:
  processed_root: data/processed/tracknet_dataset_640x360
  sequence_length: 3
  frame_stride: 1
  train_split_file: data/processed/tracknet_dataset_640x360/splits/train.txt
  val_split_file: data/processed/tracknet_dataset_640x360/splits/val.txt

train:
  experiment_name: tracknet_v1
  output_root: outputs/train
  epochs: 500
  batch_size: 2
  workers: 4
  persistent_workers: true
  prefetch_factor: 2
  optimizer: Adadelta
  lr: 1.0
  loss: cross_entropy
  device: auto
  amp: true
  tensorboard: true
  seed: 26
